# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/d9pouces/mybestpractices
    rev: 0.2.4
    hooks:
      - id: mybestpractices-git-autotag
      - id: mybestpractices-copyright
      - id: mybestpractices-third-party-update
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-inline-touching-normal
      - id: rst-directive-colons
      - id: rst-backticks
      - id: python-no-log-warn
      - id: python-no-eval
      - id: python-check-mock-methods
      - id: python-check-blanket-noqa
  - repo: https://github.com/FalconSocial/pre-commit-mirrors-pep257
    rev: v0.3.3
    hooks:
      - id: pep257
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/awebdeveloper/pre-commit-tslint
    rev: 0.0.2
    hooks:
      - id: tslint
  - repo: https://github.com/pre-commit/mirrors-csslint
    rev: v1.0.5
    hooks:
      - id: csslint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.32.0
    hooks:
      - id: eslint
  - repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.13.6
    hooks:
      - id: jshint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-byte-order-marker
      - id: check-docstring-first
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ['--max-line-length', '88', '--ignore', 'E203,E501,C901,F401,W503', '--max-complexity', '18', '--select', 'B,C,E,F,W,T4,B9']
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
    -   id: isort
        args: ['--trailing-comma', '--line-length', '88', '--multi-line', '3', '--profile', 'black', '--use-parentheses']
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args: ['--ignore', 'D100, D101, D102, D103, D104, D105, D106, D107, D203, D205, D212, D213, D400, D403, D415']
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
    -   id: shell-lint
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.40.0
    hooks:
    - id: commitizen

default_language_version:
  python: python3.8
