-   id: git-python-autotag
    name: Automatically add a new git tag when the project version is updated.
    description: This hook reads the version of your project in setup.cfg or pyproject.toml and add a git tag if this versino is changed.
    entry: git-python-autotag
    language: python
    types: [text]
    pass_filenames: false
    stages:
      - post-commit